version: '3'
services:
  solr_setup:
    image: bireme/solr:9.2.1
    user: root
    command: bash -c "chown -R 1001 /bitnami && chown -R 1001 /opt/bitnami/solr/logs"
    volumes:
      - ${SOLR_INDEX_PATH}:/bitnami
      - ${SOLR_LOG_PATH}:/opt/bitnami/solr/logs

  solr:
    depends_on:
      - solr_setup
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    image: bireme/solr:9.2.1
    ports:
      - "${CONTAINER_PORT}:8983"
    env_file:
      - .env
    environment:
      - SOLR_HEAP=${SOLR_MEMORY}
      - ZK_HOST=${ZK_HOST}
    volumes:
      - ${SOLR_INDEX_PATH}:/bitnami
      - ${SOLR_LOG_PATH}:/opt/bitnami/solr/logs

